version: '3'
volumes:
  pgdata:
services:
  backend:
    build:
      context: .
      dockerfile: docker/dev/backend/Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    volumes:
      - ./oametrix2019/openaccess:/app
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: root
      POSTGRES_PASS: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  frontend:
    build:
      context: .
      dockerfile: docker/dev/frontend/Dockerfile
    volumes:
      - ./react_oametrix/build:/app
    ports:
      - 80:80